name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: zip -rq deploy.zip * -x node_modules
      - uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deploy
      - uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: io-cool
          environment_name: IoCool-env
          version_label: "${GITHUB_SHA}""
          region: ap-southeast-2
          deployment_package: deploy.zip
          